OPENAI_API_KEY="sk-proj-5faN0NxSe9f3jm98Kli6T3BlbkFJMR02N9SoDkElJVW8DyjA"


[connections.gsheets]
spreadsheet ="https://docs.google.com/spreadsheets/d/1Y5oaJN_XDAy6iM7yVAKKqIofI1WICOmYKWCD3OVQ8E0/edit?usp=sharing"